# **Experiment 8**

### **Name : Smayan Kulkarni, SAP ID : 60009230142 , Roll Number : D100, Division : D2-2**

In [1]:
import numpy as np
from scipy import stats

1. Calculate the mean of an array of numbers [3, 6, 9, 12, 15].
Input: [3, 6, 9, 12, 15]
Output: 9.0


In [2]:
arr = np.array([3, 6, 9, 12, 15])
mean = np.mean(arr)
mean

np.float64(9.0)

2.	Determine the median of an array of numbers [7, 3, 9, 1, 5].
Input: [7, 3, 9, 1, 5]
Output: 5.0


In [3]:
arr2 = [7, 3, 9, 1, 5]
median = np.median(arr2)
median

np.float64(5.0)

3.	Find the mode of an array of integers [4, 1, 2, 2, 3, 4, 4].
Input: [4, 1, 2, 2, 3, 4, 4]
Output: 4


In [4]:
arr3 = np.array([4, 1, 2, 2, 3, 4, 4])
mode = stats.mode(arr3)[0]
mode

np.int64(4)

4.	Compute the variance of an array of numbers [2, 4, 4, 4, 5, 5, 7, 9].
Input: [2, 4, 4, 4, 5, 5, 7, 9]
Output: 4.0


In [5]:
arr4 = [2, 4, 4, 4, 5, 5, 7, 9]
var = np.var(arr4)
var

np.float64(4.0)

5.	Calculate the standard deviation of an array of numbers [10, 12, 23, 23, 16, 23, 21, 16].
Input: [10, 12, 23, 23, 16, 23, 21, 16]
Output: 4.898979485566356


In [6]:
arr5 = [10, 12, 23, 23, 16, 23, 21, 16]
std = np.std(arr4)
std

np.float64(2.0)

6.	Determine the range of an array of numbers [3, 7, 8, 5, 12, 14, 21, 13, 18].
Input: [3, 7, 8, 5, 12, 14, 21, 13, 18]
Output: 18


In [7]:
arr6 = [3, 7, 8, 5, 12, 14, 21, 13, 18]
range = np.max(arr6) - np.min(arr6)
range

np.int64(18)

7.	Compute the Pearson correlation coefficient between two arrays [1, 2, 3, 4, 5] and [2, 4, 6, 8, 10].
Input: [1, 2, 3, 4, 5], [2, 4, 6, 8, 10]
Output: 1.0


In [8]:
arr7_1 = [1, 2, 3, 4, 5]
arr7_2 = [2, 4, 6, 8, 10]
corr =np.corrcoef(arr7_1, arr7_2)[0][0]
corr

np.float64(0.9999999999999999)

8.	Create an array of 20 zeros.
Input: 20
Output: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0]


In [9]:
arr8 = np.zeros(20)
arr8

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

9.	Generate a 4x4 identity matrix.
Input: 4


In [10]:
arr_9 = np.array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]).reshape(4,4)
print(arr_9)
#or
arr_92 = np.eye(4)
print(arr_92)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


10.	Calculate the dot product of arrays [1, 2, 3] and [4, 5, 6].

In [11]:
arr10_1 = np.array([1, 2, 3])
arr10_2 = np.array([4, 5, 6])
arr10_3 = np.dot(arr10_1, arr10_2)
arr10_3

np.int64(32)

11.	Reshape an array of 12 elements into a 3x4 matrix

In [12]:
arr11 = np.random.rand(12)
arr11 = arr11.reshape(3,4)
arr11

array([[0.09749148, 0.8705868 , 0.62399143, 0.18366786],
       [0.12430513, 0.34648965, 0.95980364, 0.55452797],
       [0.27594022, 0.80647923, 0.55477256, 0.33911855]])

12.	Manually compute the Pearson correlation coefficient between two arrays [1, 2, 3, 5] and [2, 3, 4, 6] using the formula.
Input: [1, 2, 3, 5], [2, 3, 4, 6]
Output: 0.989743318610787


In [27]:
arr12_1 =  np.array([1.0,2.0, 3.0, 5.0])
arr12_2 = np.array([2.0, 3.0, 4.0, 6.0])

n = len(arr12_1)
xsum = np.sum(arr12_1)
ysum = np.sum(arr12_2)
xysum = np.dot(arr12_1, arr12_2)
xsqsum = np.sum(arr12_1**2)
ysqsum = np.sum(arr12_2**2)

numerator = float(np.array((n * (xysum)) - (xsum * ysum)))
denominator = float(np.sqrt(((n * xsqsum) - (xsum)**2) * ((n * ysqsum) - (ysum)**2)))
ans = numerator / denominator
numerator, denominator, ans,

(35.0, 35.0, 1.0)

In [2]:
# Trying gpu on a cnn

In [2]:
import tensorflow as tf
import time

# Check GPU availability
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    print("GPU is available.")
else:
    print("GPU is not available.")

# Load CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# Convert labels to one-hot encoding
y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)

# Define a tougher CNN model
def create_model():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Conv2D(64, (3, 3), activation='relu', input_shape=(32, 32, 3)),
        tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Dropout(0.25),
        tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
        tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Dropout(0.25),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(512, activation='relu'),
        tf.keras.layers.Dropout(0.5),
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

# Create and train the model
model = create_model()

# Measure training time
start_time = time.time()
history = model.fit(x_train, y_train, epochs=10, batch_size=128, verbose=1, validation_split=0.1)
end_time = time.time()

# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=0)

# Calculate GPU performance score
training_time = end_time - start_time

# Scoring system: stricter penalization for longer training time
if training_time <= 300:
    score = 10
elif training_time <= 600:
    score = 8
elif training_time <= 900:
    score = 6
elif training_time <= 1200:
    score = 4
else:
    score = 2  # Poor performance for excessively long training times

# Reduce score further if test accuracy is below a threshold
if test_acc < 0.75:
    score -= 2
elif test_acc < 0.5:
    score -= 4

# Clamp score between 0 and 10
score = max(0, min(10, score))

print(f"Test Accuracy: {test_acc:.4f}")
print(f"Training Time: {training_time:.2f} seconds")
print(f"GPU Performance Score: {score}/10")


GPU is available.
Epoch 1/10
352/352 ━━━━━━━━━━━━━━━━━━━━ 9s 17ms/step - accuracy: 0.2843 - loss: 1.8970 - val_accuracy: 0.5474 - val_loss: 1.2722
Epoch 2/10
352/352 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.5432 - loss: 1.2795 - val_accuracy: 0.6290 - val_loss: 1.0438
Epoch 3/10
352/352 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.6214 - loss: 1.0702 - val_accuracy: 0.6996 - val_loss: 0.8621
Epoch 4/10
352/352 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.6737 - loss: 0.9267 - val_accuracy: 0.7274 - val_loss: 0.7818
Epoch 5/10
352/352 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7077 - loss: 0.8333 - val_accuracy: 0.7498 - val_loss: 0.7263
Epoch 6/10
352/352 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7321 - loss: 0.7585 - val_accuracy: 0.7552 - val_loss: 0.7009
Epoch 7/10
352/352 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7549 - loss: 0.6941 - val_accuracy: 0.7622 - val_loss: 0.6791
Epoch 8/10
352/352 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7713 - loss: 0.6455

In [28]:
arr7_1 = np.array([1.0,2.0, 3.0, 5.0])
arr7_2 = np.array([2.0, 3.0, 4.0, 6.0])
corr =np.corrcoef(arr7_1, arr7_2)[0][0]
corr

np.float64(1.0)