# **Experiment 7**

### **Name : Smayan Kulkarni, SAP ID : 60009230142 , Roll Number : D100, Division : D2-2**

In [1]:
import numpy as np

1.	Create a 3x3 matrix of random integers between 1 and 10 and find the total sum of its elements.

In [2]:
arr1 = np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2.	Generate a 4x4 matrix of random numbers and compute the average of all its elements.


In [3]:
arr2 = np.arange(16).reshape(4,4)
arr2.mean()

7.5

3.	Create a 2x3 matrix and find the sum of all elements in the second row.


In [4]:
arr3 = np.random.rand(6).reshape(2,3)
print(arr3)
for i in range(2) :
    print(arr3[i].sum())

[[0.21589245 0.08186401 0.4689839 ]
 [0.12366065 0.69405717 0.21344663]]
0.7667403565378322
1.0311644470384016


4.	Generate a 5x5 matrix of random integers and determine the highest value in each column.


In [5]:
np.random.seed(2384)
arr3 = np.random.rand(25).reshape(5,5)
print(arr3)
arr3[0::1][2]

[[0.77168925 0.2007156  0.1531792  0.33632183 0.17543724]
 [0.03725477 0.91231499 0.23453876 0.29892252 0.22934923]
 [0.38091769 0.2755385  0.86899951 0.99916212 0.61763016]
 [0.06761361 0.40706373 0.89343895 0.61966237 0.80292686]
 [0.50207052 0.5111385  0.15958073 0.63560156 0.16881159]]


array([0.38091769, 0.2755385 , 0.86899951, 0.99916212, 0.61763016])

5.	Create a 4x4 matrix and calculate the sum of its main diagonal elements.



In [6]:
arr4 = np.random.rand(16).reshape(4,4)
sum = 0
for i in range(4):
    for j in range(4):
        if(i==j):
            sum+=arr4[i][j]
sum   

3.5401223238135895

6.	Generate a 3x3 matrix and find the smallest value among all its elements.


In [7]:
arr6 = np.random.rand(9).reshape(3,3)
minimum = min(arr6[0])
for i in range(len(arr6)):
    for j in range(len(arr6)):
        if arr6[i][j] < minimum:
            minimum = arr6[i][j]
print(arr6)           
minimum

[[0.02193189 0.38540863 0.94458542]
 [0.04809152 0.43420625 0.91827789]
 [0.51904897 0.56734419 0.5434014 ]]


0.021931888057477367

7.	Create a 4x4 matrix of random integers between 1 and 20 and compute the sum of all elements that are greater than 10.


In [8]:
matrix = np.random.randint(1, 21, size=(4, 4))
print(matrix)
sum_greater_than_10 = np.sum(matrix[matrix > 10])
print(sum_greater_than_10)


[[ 3  7 19 14]
 [ 8  4 14  5]
 [18 15  4 18]
 [ 3 13  2 20]]
131


8.	Generate a 5x5 matrix of random numbers and find the mean of the maximum values of each row.


In [9]:
arr8 = np.random.randint(1,100, size = (5,5))
maxvals = [0]*5
print(arr8)
for i in range(arr8.shape[1]):
    for j in range(arr8.shape[1]):
        if(maxvals[i] < arr8[i][j]):
            maxvals[i] = arr8[i][j]
    
print(f'The mean neded is: {np.mean(maxvals)}')
        

[[85 45 44 32 49]
 [11 90 20  6 38]
 [62 16 12 73 67]
 [46 71 34  1 55]
 [75 56 19 97 70]]
The mean neded is: 83.2


9.	Create a 3x3 matrix and calculate the difference between the sum of the elements in the first row and the sum of the elements in the last row.


In [10]:
arr9 = np.random.randint(1,50, size = (3,3))
diff = np.sum(arr9[-1]) - np.sum(arr9[0])
diff

-26

10.	Generate a 6x6 matrix of random integers and replace all values below the median with zero.


In [11]:
arr10 = np.random.randint(1, 100, size = (6,6))
median = np.median(arr10)
print(arr10, '\n')
for i in range(len(arr6)):
    for j in range(len(arr6)):
        if arr10[i][j] < median: 
            arr10[i][j] = 0

print(median, '\n')
print(arr10)

[[77 60 68 91 19 77]
 [37 76 46 94 77 72]
 [56 22 89 33 67 34]
 [25 60 15 30 63 84]
 [24 10 92 94 93 27]
 [14 10 32 87 10 97]] 

60.0 

[[77 60 68 91 19 77]
 [ 0 76  0 94 77 72]
 [ 0  0 89 33 67 34]
 [25 60 15 30 63 84]
 [24 10 92 94 93 27]
 [14 10 32 87 10 97]]


11.	Create a 4x4 matrix and compute the sum of elements in the upper triangular part of the matrix.


In [12]:
np.random.seed(42) ## cuz output kept changing always
arr11 = np.random.randint(1, 100, size = (4,4),)
print(arr11)
sum = 0

for i in range(len(arr11)):
    for j in range(i, 4):
        sum = sum + arr11[i][j]

print(sum)


[[52 93 15 72]
 [61 21 83 87]
 [75 75 88 24]
 [ 3 22 53  2]]
537


12.	Generate a 3x4 matrix of random values and find the standard deviation of the elements in the third column.

In [14]:
matrix = np.random.rand(3, 4)
std_dev_third_column = np.std(matrix[:, 2])
print(std_dev_third_column)

0.020312146490465754
