# **Experiment 8**

### **Name : Smayan Kulkarni, SAP ID : 60009230142 , Roll Number : D100, Division : D2-2**

In [1]:
import numpy as np
from scipy import stats

1. Calculate the mean of an array of numbers [3, 6, 9, 12, 15].
Input: [3, 6, 9, 12, 15]
Output: 9.0


In [2]:
arr = np.array([3, 6, 9, 12, 15])
mean = np.mean(arr)
mean

np.float64(9.0)

2.	Determine the median of an array of numbers [7, 3, 9, 1, 5].
Input: [7, 3, 9, 1, 5]
Output: 5.0


In [3]:
arr2 = [7, 3, 9, 1, 5]
median = np.median(arr2)
median

np.float64(5.0)

3.	Find the mode of an array of integers [4, 1, 2, 2, 3, 4, 4].
Input: [4, 1, 2, 2, 3, 4, 4]
Output: 4


In [4]:
arr3 = np.array([4, 1, 2, 2, 3, 4, 4])
mode = stats.mode(arr3)[0]
mode

np.int64(4)

4.	Compute the variance of an array of numbers [2, 4, 4, 4, 5, 5, 7, 9].
Input: [2, 4, 4, 4, 5, 5, 7, 9]
Output: 4.0


In [5]:
arr4 = [2, 4, 4, 4, 5, 5, 7, 9]
var = np.var(arr4)
var

np.float64(4.0)

5.	Calculate the standard deviation of an array of numbers [10, 12, 23, 23, 16, 23, 21, 16].
Input: [10, 12, 23, 23, 16, 23, 21, 16]
Output: 4.898979485566356


In [6]:
arr5 = [10, 12, 23, 23, 16, 23, 21, 16]
std = np.std(arr4)
std

np.float64(2.0)

6.	Determine the range of an array of numbers [3, 7, 8, 5, 12, 14, 21, 13, 18].
Input: [3, 7, 8, 5, 12, 14, 21, 13, 18]
Output: 18


In [7]:
arr6 = [3, 7, 8, 5, 12, 14, 21, 13, 18]
range = np.max(arr6) - np.min(arr6)
range

np.int64(18)

7.	Compute the Pearson correlation coefficient between two arrays [1, 2, 3, 4, 5] and [2, 4, 6, 8, 10].
Input: [1, 2, 3, 4, 5], [2, 4, 6, 8, 10]
Output: 1.0


In [8]:
arr7_1 = [1, 2, 3, 4, 5]
arr7_2 = [2, 4, 6, 8, 10]
corr =np.corrcoef(arr7_1, arr7_2)[0][0]
corr

np.float64(0.9999999999999999)

8.	Create an array of 20 zeros.
Input: 20
Output: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0]


In [9]:
arr8 = np.zeros(20)
arr8

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

9.	Generate a 4x4 identity matrix.
Input: 4


In [10]:
arr_9 = np.array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]).reshape(4,4)
print(arr_9)
#or
arr_92 = np.eye(4)
print(arr_92)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


10.	Calculate the dot product of arrays [1, 2, 3] and [4, 5, 6].

In [11]:
arr10_1 = np.array([1, 2, 3])
arr10_2 = np.array([4, 5, 6])
arr10_3 = np.dot(arr10_1, arr10_2)
arr10_3

np.int64(32)

11.	Reshape an array of 12 elements into a 3x4 matrix

In [12]:
arr11 = np.random.rand(12)
arr11 = arr11.reshape(3,4)
arr11

array([[0.09749148, 0.8705868 , 0.62399143, 0.18366786],
       [0.12430513, 0.34648965, 0.95980364, 0.55452797],
       [0.27594022, 0.80647923, 0.55477256, 0.33911855]])

12.	Manually compute the Pearson correlation coefficient between two arrays [1, 2, 3, 5] and [2, 3, 4, 6] using the formula.
Input: [1, 2, 3, 5], [2, 3, 4, 6]
Output: 0.989743318610787


In [27]:
arr12_1 =  np.array([1.0,2.0, 3.0, 5.0])
arr12_2 = np.array([2.0, 3.0, 4.0, 6.0])

n = len(arr12_1)
xsum = np.sum(arr12_1)
ysum = np.sum(arr12_2)
xysum = np.dot(arr12_1, arr12_2)
xsqsum = np.sum(arr12_1**2)
ysqsum = np.sum(arr12_2**2)

numerator = float(np.array((n * (xysum)) - (xsum * ysum)))
denominator = float(np.sqrt(((n * xsqsum) - (xsum)**2) * ((n * ysqsum) - (ysum)**2)))
ans = numerator / denominator
numerator, denominator, ans,

(35.0, 35.0, 1.0)

In [28]:
arr7_1 = np.array([1.0,2.0, 3.0, 5.0])
arr7_2 = np.array([2.0, 3.0, 4.0, 6.0])
corr =np.corrcoef(arr7_1, arr7_2)[0][0]
corr

np.float64(1.0)