# **Experiment 7**

### **Name : Smayan Kulkarni, SAP ID : 60009230142 , Roll Number : D100, Division : D2-2**

In [43]:
import numpy as np

1.	Create a 3x3 matrix of random integers between 1 and 10 and find the total sum of its elements.

In [44]:
arr1 = np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2.	Generate a 4x4 matrix of random numbers and compute the average of all its elements.


In [45]:
arr2 = np.arange(16).reshape(4,4)
arr2.mean()

np.float64(7.5)

3.	Create a 2x3 matrix and find the sum of all elements in the second row.


In [46]:
arr3 = np.random.rand(6).reshape(2,3)
print(arr3)
for i in range(2) :
    print(arr3[i].sum())

[[0.77832938 0.81218706 0.80593382]
 [0.47383528 0.70121873 0.8469607 ]]
2.396450255193513
2.0220147173488


4.	Generate a 5x5 matrix of random integers and determine the highest value in each column.


In [47]:
np.random.seed(2384)
arr3 = np.random.rand(25).reshape(5,5)
print(arr3)
arr3[0::1][2]

[[0.77168925 0.2007156  0.1531792  0.33632183 0.17543724]
 [0.03725477 0.91231499 0.23453876 0.29892252 0.22934923]
 [0.38091769 0.2755385  0.86899951 0.99916212 0.61763016]
 [0.06761361 0.40706373 0.89343895 0.61966237 0.80292686]
 [0.50207052 0.5111385  0.15958073 0.63560156 0.16881159]]


array([0.38091769, 0.2755385 , 0.86899951, 0.99916212, 0.61763016])

5.	Create a 4x4 matrix and calculate the sum of its main diagonal elements.



6.	Generate a 3x3 matrix and find the smallest value among all its elements.


7.	Create a 4x4 matrix of random integers between 1 and 20 and compute the sum of all elements that are greater than 10.


8.	Generate a 5x5 matrix of random numbers and find the mean of the maximum values of each row.


9.	Create a 3x3 matrix and calculate the difference between the sum of the elements in the first row and the sum of the elements in the last row.


10.	Generate a 6x6 matrix of random integers and replace all values below the median with zero.


11.	Create a 4x4 matrix and compute the sum of elements in the upper triangular part of the matrix.


12.	Generate a 3x4 matrix of random values and find the standard deviation of the elements in the third column.