# **Experiment 8**

### **Name : Smayan Kulkarni, SAP ID : 60009230142 , Roll Number : D100, Division : D2-2**

In [1]:
import numpy as np
from scipy import stats

1. Calculate the mean of an array of numbers [3, 6, 9, 12, 15].
Input: [3, 6, 9, 12, 15]
Output: 9.0


In [2]:
arr = np.array([3, 6, 9, 12, 15])
mean = np.mean(arr)
mean

np.float64(9.0)

2.	Determine the median of an array of numbers [7, 3, 9, 1, 5].
Input: [7, 3, 9, 1, 5]
Output: 5.0


In [3]:
arr2 = [7, 3, 9, 1, 5]
median = np.median(arr2)
median

np.float64(5.0)

3.	Find the mode of an array of integers [4, 1, 2, 2, 3, 4, 4].
Input: [4, 1, 2, 2, 3, 4, 4]
Output: 4


In [4]:
arr3 = np.array([4, 1, 2, 2, 3, 4, 4])
mode = stats.mode(arr3)[0]
mode

np.int64(4)

4.	Compute the variance of an array of numbers [2, 4, 4, 4, 5, 5, 7, 9].
Input: [2, 4, 4, 4, 5, 5, 7, 9]
Output: 4.0


In [5]:
arr4 = [2, 4, 4, 4, 5, 5, 7, 9]
var = np.var(arr4)
var

np.float64(4.0)

5.	Calculate the standard deviation of an array of numbers [10, 12, 23, 23, 16, 23, 21, 16].
Input: [10, 12, 23, 23, 16, 23, 21, 16]
Output: 4.898979485566356


In [6]:
arr5 = [10, 12, 23, 23, 16, 23, 21, 16]
std = np.std(arr4)
std

np.float64(2.0)

6.	Determine the range of an array of numbers [3, 7, 8, 5, 12, 14, 21, 13, 18].
Input: [3, 7, 8, 5, 12, 14, 21, 13, 18]
Output: 18


In [7]:
arr6 = [3, 7, 8, 5, 12, 14, 21, 13, 18]
range = np.max(arr6) - np.min(arr6)
range

np.int64(18)

7.	Compute the Pearson correlation coefficient between two arrays [1, 2, 3, 4, 5] and [2, 4, 6, 8, 10].
Input: [1, 2, 3, 4, 5], [2, 4, 6, 8, 10]
Output: 1.0


In [8]:
arr7_1 = [1, 2, 3, 4, 5]
arr7_2 = [2, 4, 6, 8, 10]
corr =np.corrcoef(arr7_1, arr7_2)[0][0]
corr

np.float64(0.9999999999999999)

8.	Create an array of 20 zeros.
Input: 20
Output: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0]


In [9]:
arr8 = np.zeros(20)
arr8

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

9.	Generate a 4x4 identity matrix.
Input: 4


In [10]:
arr_9 = np.array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]).reshape(4,4)
print(arr_9)
#or
arr_92 = np.eye(4)
print(arr_92)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


10.	Calculate the dot product of arrays [1, 2, 3] and [4, 5, 6].

In [11]:
arr10_1 = np.array([1, 2, 3])
arr10_2 = np.array([4, 5, 6])
arr10_3 = np.dot(arr10_1, arr10_2)
arr10_3

np.int64(32)

11.	Reshape an array of 12 elements into a 3x4 matrix

In [12]:
arr11 = np.random.rand(12)
arr11 = arr11.reshape(3,4)
arr11

array([[0.09749148, 0.8705868 , 0.62399143, 0.18366786],
       [0.12430513, 0.34648965, 0.95980364, 0.55452797],
       [0.27594022, 0.80647923, 0.55477256, 0.33911855]])

12.	Manually compute the Pearson correlation coefficient between two arrays [1, 2, 3, 5] and [2, 3, 4, 6] using the formula.
Input: [1, 2, 3, 5], [2, 3, 4, 6]
Output: 0.989743318610787


In [27]:
arr12_1 =  np.array([1.0,2.0, 3.0, 5.0])
arr12_2 = np.array([2.0, 3.0, 4.0, 6.0])

n = len(arr12_1)
xsum = np.sum(arr12_1)
ysum = np.sum(arr12_2)
xysum = np.dot(arr12_1, arr12_2)
xsqsum = np.sum(arr12_1**2)
ysqsum = np.sum(arr12_2**2)

numerator = float(np.array((n * (xysum)) - (xsum * ysum)))
denominator = float(np.sqrt(((n * xsqsum) - (xsum)**2) * ((n * ysqsum) - (ysum)**2)))
ans = numerator / denominator
numerator, denominator, ans,

(35.0, 35.0, 1.0)

In [2]:
# Trying gpu on a cnn

In [ ]:
import tensorflow as tf
import time

# Check GPU availability
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    print("GPU is available.")
else:
    print("GPU is not available.")

# Load CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# Convert labels to one-hot encoding
y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)

# Define a tougher CNN model
def create_model():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Conv2D(64, (3, 3), activation='relu', input_shape=(32, 32, 3)),
        tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Dropout(0.25),
        tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
        tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Dropout(0.25),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(512, activation='relu'),
        tf.keras.layers.Dropout(0.5),
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

# Create and train the model
model = create_model()

# Measure training time
start_time = time.time()
history = model.fit(x_train, y_train, epochs=10, batch_size=128, verbose=1, validation_split=0.1)
end_time = time.time()

# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=0)

# Calculate GPU performance score
training_time = end_time - start_time

# Scoring system: stricter penalization for longer training time
if training_time <= 300:
    score = 10
elif training_time <= 600:
    score = 8
elif training_time <= 900:
    score = 6
elif training_time <= 1200:
    score = 4
else:
    score = 2  # Poor performance for excessively long training times

# Reduce score further if test accuracy is below a threshold
if test_acc < 0.75:
    score -= 2
elif test_acc < 0.5:
    score -= 4

# Clamp score between 0 and 10
score = max(0, min(10, score))

print(f"Test Accuracy: {test_acc:.4f}")
print(f"Training Time: {training_time:.2f} seconds")
print(f"GPU Performance Score: {score}/10")


2024-12-24 18:15:38.032439: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-12-24 18:15:38.202851: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1735044338.273181    6010 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1735044338.295187    6010 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-24 18:15:38.439274: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

GPU is available.


/home/smayan/Desktop/AI-ML-DS/AI-and-ML-Course/.conda/lib/python3.11/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
I0000 00:00:1735044341.395567    6010 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9148 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4070 SUPER, pci bus id: 0000:01:00.0, compute capability: 8.9


Epoch 1/5


I0000 00:00:1735044342.806060   20525 service.cc:148] XLA service 0x7c67f400a9e0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1735044342.806170   20525 service.cc:156]   StreamExecutor device (0): NVIDIA GeForce RTX 4070 SUPER, Compute Capability 8.9
2024-12-24 18:15:42.824029: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1735044342.904687   20525 cuda_dnn.cc:529] Loaded cuDNN version 90600


 88/704 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1972 - loss: 2.1651

I0000 00:00:1735044344.034758   20525 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


704/704 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.3705 - loss: 1.7338 - val_accuracy: 0.5546 - val_loss: 1.2687
Epoch 2/5
704/704 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5707 - loss: 1.2191 - val_accuracy: 0.5960 - val_loss: 1.1401
Epoch 3/5
704/704 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6313 - loss: 1.0472 - val_accuracy: 0.6532 - val_loss: 0.9909
Epoch 4/5
704/704 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6732 - loss: 0.9396 - val_accuracy: 0.6692 - val_loss: 0.9615
Epoch 5/5
704/704 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7000 - loss: 0.8553 - val_accuracy: 0.6736 - val_loss: 0.9577


2024-12-24 18:15:54.055183: I external/local_xla/xla/stream_executor/cuda/cuda_asm_compiler.cc:397] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_78', 4 bytes spill stores, 4 bytes spill loads



Test Accuracy: 0.6649
Training Time: 11.91 seconds
GPU Performance Score: 9.88/10


In [28]:
arr7_1 = np.array([1.0,2.0, 3.0, 5.0])
arr7_2 = np.array([2.0, 3.0, 4.0, 6.0])
corr =np.corrcoef(arr7_1, arr7_2)[0][0]
corr

np.float64(1.0)