In [1]:
import numpy as np

## 1. Datatypes and Attributes

In [2]:
#Numpys main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],[4,5,6]])

In [5]:
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               
               [[10,11,12],[13,14,15],[16,17,18]]])

In [6]:
a2
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
a2
import pandas as pd

In [15]:
df = pd.DataFrame(a2)

In [16]:
df

0  1  2
0  1  2  3
1  4  5  6

# 2. Creating Numpy Arrays

In [17]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int64')

In [19]:
ones = np.ones((2,3))

In [20]:
ones


array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
ones.dtype

dtype('float64')

In [22]:
type(ones)

numpy.ndarray

In [23]:
zeros = np.zeros((2,3))

In [24]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
range_array = np.arange(0,10,3)

In [26]:
range_array

array([0, 3, 6, 9])

In [27]:
random_array = np.random.randint(0,100, size = (5,6))

In [28]:
random_array

array([[26, 49, 65,  5, 77,  3],
       [44, 29, 25, 54, 36, 13],
       [64,  9,  1,  8, 98, 82],
       [82, 51, 18, 90, 78, 35],
       [40, 62, 83, 10, 79, 45]])

In [29]:
random_arr2 = np.random.random((3,4))

In [30]:
random_arr2.shape

(3, 4)

In [31]:
random_arr3 = np.random.rand(5,3)

In [32]:
random_arr3

array([[0.35344892, 0.64256316, 0.49371616],
       [0.1645702 , 0.62009265, 0.91092674],
       [0.35616901, 0.21930322, 0.40361189],
       [0.27606831, 0.67060227, 0.88819374],
       [0.08284556, 0.90393029, 0.12755262]])

In [33]:
# Psuedo-random numbers

In [34]:
np.random.seed(seed= 7)
random_arr5 = np.random.random((5,3))
random_arr5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing Arrays and Matrices

In [35]:
np.unique(random_arr2)

array([0.05312172, 0.07890223, 0.29851655, 0.36002081, 0.40343315,
       0.4265384 , 0.6923637 , 0.78762231, 0.82460797, 0.85785953,
       0.98030356, 0.98344682])

In [36]:
a1


array([1, 2, 3])

In [37]:
a1[0]

1

In [38]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
a2[0]

array([1, 2, 3])

In [40]:
a2[1]

array([4, 5, 6])

In [41]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [42]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a3[:2,:1,:3] # Slicing

array([[[ 1,  2,  3]],

       [[10, 11, 12]]])

In [44]:
np.random.seed(seed=120)
a4 = np.random.randint(10, size=(2,3,4,5))

In [45]:
a4

array([[[[7, 0, 8, 4, 1],
         [7, 1, 3, 8, 9],
         [4, 9, 9, 6, 7],
         [9, 1, 9, 4, 5]],

        [[7, 2, 2, 2, 0],
         [0, 7, 4, 2, 2],
         [4, 8, 5, 6, 4],
         [1, 9, 2, 0, 5]],

        [[7, 5, 7, 8, 4],
         [2, 1, 6, 9, 5],
         [6, 1, 5, 7, 8],
         [7, 4, 8, 9, 7]]],


       [[[8, 5, 6, 0, 5],
         [8, 6, 8, 5, 4],
         [1, 9, 4, 5, 7],
         [9, 1, 2, 9, 5]],

        [[5, 8, 9, 2, 1],
         [6, 1, 6, 4, 4],
         [7, 8, 2, 8, 7],
         [3, 4, 4, 5, 3]],

        [[8, 6, 1, 6, 5],
         [5, 3, 6, 6, 4],
         [6, 8, 8, 5, 6],
         [3, 3, 7, 8, 0]]]])

In [46]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [47]:
a4[:,:,:,:4]

array([[[[7, 0, 8, 4],
         [7, 1, 3, 8],
         [4, 9, 9, 6],
         [9, 1, 9, 4]],

        [[7, 2, 2, 2],
         [0, 7, 4, 2],
         [4, 8, 5, 6],
         [1, 9, 2, 0]],

        [[7, 5, 7, 8],
         [2, 1, 6, 9],
         [6, 1, 5, 7],
         [7, 4, 8, 9]]],


       [[[8, 5, 6, 0],
         [8, 6, 8, 5],
         [1, 9, 4, 5],
         [9, 1, 2, 9]],

        [[5, 8, 9, 2],
         [6, 1, 6, 4],
         [7, 8, 2, 8],
         [3, 4, 4, 5]],

        [[8, 6, 1, 6],
         [5, 3, 6, 6],
         [6, 8, 8, 5],
         [3, 3, 7, 8]]]])

In [48]:
a5 = np.random.randint(10, 50, size=(2,3,4,5,6))

In [49]:
a5

array([[[[[26, 37, 34, 11, 18, 33],
          [24, 11, 13, 40, 15, 25],
          [13, 28, 29, 43, 21, 33],
          [32, 17, 27, 32, 32, 14],
          [23, 20, 29, 48, 12, 25]],

         [[46, 19, 32, 39, 46, 37],
          [14, 47, 26, 28, 22, 17],
          [23, 25, 11, 39, 35, 36],
          [44, 41, 16, 14, 28, 34],
          [30, 18, 44, 25, 37, 36]],

         [[30, 21, 32, 37, 20, 18],
          [35, 20, 16, 24, 16, 35],
          [18, 38, 48, 30, 29, 33],
          [41, 21, 37, 29, 26, 13],
          [30, 38, 46, 36, 20, 10]],

         [[37, 11, 44, 15, 49, 48],
          [47, 39, 40, 29, 37, 26],
          [27, 18, 19, 30, 42, 16],
          [17, 26, 12, 32, 17, 33],
          [37, 42, 42, 38, 10, 46]]],


        [[[31, 38, 22, 36, 33, 12],
          [33, 30, 17, 12, 47, 12],
          [39, 25, 46, 35, 20, 10],
          [16, 40, 33, 41, 39, 12],
          [35, 18, 31, 21, 21, 26]],

         [[49, 48, 39, 16, 28, 15],
          [12, 30, 46, 40, 47, 48],
          [30, 2

In [50]:
a5[:1,:2,:,:4,:3]

array([[[[[26, 37, 34],
          [24, 11, 13],
          [13, 28, 29],
          [32, 17, 27]],

         [[46, 19, 32],
          [14, 47, 26],
          [23, 25, 11],
          [44, 41, 16]],

         [[30, 21, 32],
          [35, 20, 16],
          [18, 38, 48],
          [41, 21, 37]],

         [[37, 11, 44],
          [47, 39, 40],
          [27, 18, 19],
          [17, 26, 12]]],


        [[[31, 38, 22],
          [33, 30, 17],
          [39, 25, 46],
          [16, 40, 33]],

         [[49, 48, 39],
          [12, 30, 46],
          [30, 24, 20],
          [46, 13, 15]],

         [[35, 21, 30],
          [25, 46, 16],
          [35, 47, 18],
          [46, 21, 38]],

         [[47, 28, 11],
          [38, 48, 18],
          [42, 37, 26],
          [32, 29, 45]]]]])

## Manipulating and Comparing Arrays

### Arithmetic

In [51]:
a1


array([1, 2, 3])

In [52]:
ones = np.ones(3)

In [53]:
a1 + ones

array([2., 3., 4.])

In [54]:
a1 - ones

array([0., 1., 2.])

In [55]:
a1* ones



array([1., 2., 3.])

In [56]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
a1 * a2


array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [58]:
a1/a2

array([[1.  , 1.  , 1.  ],
       [0.25, 0.4 , 0.5 ]])

In [59]:
a1//a2

array([[1, 1, 1],
       [0, 0, 0]])

In [60]:
a2 **a1

array([[  1,   4,  27],
       [  4,  25, 216]])

In [61]:
a1**4

array([ 1, 16, 81])

In [62]:
a2**5

array([[   1,   32,  243],
       [1024, 3125, 7776]])

In [63]:
a4

array([[[[7, 0, 8, 4, 1],
         [7, 1, 3, 8, 9],
         [4, 9, 9, 6, 7],
         [9, 1, 9, 4, 5]],

        [[7, 2, 2, 2, 0],
         [0, 7, 4, 2, 2],
         [4, 8, 5, 6, 4],
         [1, 9, 2, 0, 5]],

        [[7, 5, 7, 8, 4],
         [2, 1, 6, 9, 5],
         [6, 1, 5, 7, 8],
         [7, 4, 8, 9, 7]]],


       [[[8, 5, 6, 0, 5],
         [8, 6, 8, 5, 4],
         [1, 9, 4, 5, 7],
         [9, 1, 2, 9, 5]],

        [[5, 8, 9, 2, 1],
         [6, 1, 6, 4, 4],
         [7, 8, 2, 8, 7],
         [3, 4, 4, 5, 3]],

        [[8, 6, 1, 6, 5],
         [5, 3, 6, 6, 4],
         [6, 8, 8, 5, 6],
         [3, 3, 7, 8, 0]]]])

In [64]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

### Aggregation

In [65]:
list = [1,2,3]

In [66]:
type(list) 

list

In [67]:
sum(list)

6

In [68]:
a1

array([1, 2, 3])

In [69]:
type(a1)

numpy.ndarray

In [70]:
np.sum(a1)

6

#### Use puthons method 'sum()' on python data types and numpys 'np.sum()' method on numpy arrays 

In [71]:
massivearr = np.random.random(100)
massivearr.size

100

In [72]:
%timeit sum(massivearr) #Pythons sum
%timeit np.sum(massivearr) #Numpy sum

8.95 μs ± 1.17 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
2.96 μs ± 157 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [73]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
a2.mean()

3.5

In [75]:
np.std(a3) # Standard Deviance is the measure of how spread out a group of numbers if from the mean

5.188127472091127

In [76]:
np.var(a2)  # Variance is the measure of average degree to which each number if different to the mean
#High Variance : Higher range
#Low Variance : Lower Range

2.9166666666666665

In [77]:
np.sqrt(np.var(a3))

5.188127472091127

### Reshaping and Transposing

In [78]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [79]:
a2.shape

(2, 3)

In [80]:
a3.shape

(2, 3, 3)

In [81]:
a2.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [82]:
a2reshape = a2.reshape(2,3,1)

In [83]:
a2reshape * a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

In [84]:
a2.T  #Transpose : switching the axes

array([[1, 4],
       [2, 5],
       [3, 6]])

In [85]:
a2.T.shape


(3, 2)

#### Dot Product

In [86]:
np.random.seed(0)
mat1 = np.random.randint(15,size = (5,3))
mat2 = np.random.randint(15,size = (5,3))

In [87]:
mat1

array([[12,  5,  0],
       [ 3, 11,  3],
       [ 7,  9,  3],
       [ 5,  2,  4],
       [ 7,  6,  8]])

In [88]:
mat2

array([[ 8, 12, 10],
       [ 1,  6,  7],
       [ 7, 14,  8],
       [ 1,  5,  9],
       [13,  8,  9]])

In [89]:
#Multiplying element wise (Hardamard Product)
mat1*mat2

array([[ 96,  60,   0],
       [  3,  66,  21],
       [ 49, 126,  24],
       [  5,  10,  36],
       [ 91,  48,  72]])

In [90]:
#Dot Product
np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [ ]:
np.dot(mat1.T,mat2)

array([[244, 341, 305],
       [194, 310, 271],
       [132, 144, 153]])

In [ ]:
mat1.T.shape

(3, 5)

### Dot Product (nut butter sales)

In [ ]:
np.random.seed(50)
sales_amounts = np.random.randint(20, size = (5,3))
sales_amounts

array([[16,  0, 11],
       [13,  1,  4],
       [ 6,  5,  6],
       [13,  5,  2],
       [ 7, 15,  4]])

In [ ]:
# Create a weekly sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tue", "Wed", "Thu", "Fri"],columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [ ]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon             16              0             11
Tue             13              1              4
Wed              6              5              6
Thu             13              5              2
Fri              7             15              4

In [ ]:
prices = np.array([10,8,12])

In [ ]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"], columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [ ]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [ ]:
prices.shape

(3,)

In [ ]:
sales_amounts.shape

(5, 3)

In [ ]:
total_sale = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [91]:
#Shapes arent aligned , lets transpose
total_sale = prices.dot(sales_amounts.T)

NameError: name 'prices' is not defined

In [92]:
total_sale 

NameError: name 'total_sale' is not defined

In [93]:
butter_prices

NameError: name 'butter_prices' is not defined

In [ ]:
weekly_sales.T

Mon  Tue  Wed  Thu  Fri
Almond Butter   16   13    6   13    7
Peanut Butter    0    1    5    5   15
Cashew Butter   11    4    6    2    4

In [94]:
daily_sales = butter_prices.dot(weekly_sales.T)

NameError: name 'butter_prices' is not defined

In [ ]:
daily_sales

Mon  Tue  Wed  Thu  Fri
Price  292  186  172  194  238

In [95]:
weekly_sales["Total ($)"] = daily_sales.T

NameError: name 'daily_sales' is not defined

In [ ]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total  Total ($)
Mon             16              0             11    292        292
Tue             13              1              4    186        186
Wed              6              5              6    172        172
Thu             13              5              2    194        194
Fri              7             15              4    238        238

In [96]:
a1 >a2

array([[False, False, False],
       [False, False, False]])

In [97]:
a1<5

array([ True,  True,  True])

In [98]:
a1==a1

array([ True,  True,  True])

In [99]:
a1==a2

array([[ True,  True,  True],
       [False, False, False]])

### Sorting Arrays

In [100]:
np.sort(a2)

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
randomarr = np.random.randint(20, size = (2,4))
randomarr

array([[19, 16, 19,  5],
       [15, 15,  0, 18]])

In [102]:
np.sort(randomarr)

array([[ 5, 16, 19, 19],
       [ 0, 15, 15, 18]])

In [103]:
np.argsort(randomarr)

array([[3, 1, 0, 2],
       [2, 0, 1, 3]])

In [104]:
a1

array([1, 2, 3])

In [105]:
np.argsort(a1)

array([0, 1, 2])

In [106]:
np.argmin(randomarr)

6

In [107]:
np.argmax(randomarr,axis = 0)

array([0, 0, 0, 1])

In [108]:
np.argmax(randomarr,axis = 1)

array([0, 3])

### Images to Numpy Arrays

In [109]:
from matplotlib.image import imread

img = imread("/home/smayan/Desktop/AI-ML-DS/sample_project/6-step-ml-framework.png")
print(type(img))

<class 'numpy.ndarray'>


In [110]:
img.size, img.shape, img.ndim

(17127936, (1296, 3304, 4), 3)

In [111]:
img[:5]

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)