In [1]:
import numpy as np

## 1. Datatypes and Attributes

In [2]:
#Numpys main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],[4,5,6]])

In [5]:
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               
               [[10,11,12],[13,14,15],[16,17,18]]])

In [6]:
a2
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
a2
import pandas as pd

In [15]:
df = pd.DataFrame(a2)

In [16]:
df

0  1  2
0  1  2  3
1  4  5  6

# 2. Creating Numpy Arrays