In [1]:
import numpy as np

## 1. Datatypes and Attributes

In [2]:
#Numpys main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],[4,5,6]])

In [5]:
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               
               [[10,11,12],[13,14,15],[16,17,18]]])

In [6]:
a2
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
a2
import pandas as pd

In [15]:
df = pd.DataFrame(a2)

In [16]:
df

0  1  2
0  1  2  3
1  4  5  6

# 2. Creating Numpy Arrays

In [17]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int64')

In [19]:
ones = np.ones((2,3))

In [20]:
ones


array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
ones.dtype

dtype('float64')

In [22]:
type(ones)

numpy.ndarray

In [23]:
zeros = np.zeros((2,3))

In [24]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
range_array = np.arange(0,10,3)

In [26]:
range_array

array([0, 3, 6, 9])

In [27]:
random_array = np.random.randint(0,100, size = (5,6))

In [28]:
random_array

array([[77, 49, 37, 50, 51, 89],
       [42, 79, 42, 89, 93, 77],
       [66, 46, 92, 79,  0, 18],
       [84, 39, 66, 14, 14, 27],
       [ 2, 58, 45, 26, 78, 89]])

In [29]:
random_arr2 = np.random.random((3,4))

In [30]:
random_arr2.shape

(3, 4)

In [31]:
random_arr3 = np.random.rand(5,3)

In [32]:
random_arr3

array([[0.11409168, 0.71133658, 0.4697037 ],
       [0.43831218, 0.04300405, 0.72490796],
       [0.14382928, 0.75035066, 0.58099187],
       [0.46154489, 0.05303726, 0.31251539],
       [0.30610098, 0.24742005, 0.74223449]])

In [33]:
# Psuedo-random numbers

In [34]:
np.random.seed(seed= 7)
random_arr5 = np.random.random((5,3))
random_arr5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing Arrays and Matrices

In [36]:
np.unique(random_arr2)

array([0.03729912, 0.08402239, 0.0862498 , 0.09998248, 0.29453192,
       0.41188494, 0.56489055, 0.76813592, 0.77401334, 0.85781311,
       0.91269642, 0.98925846])

In [37]:
a1


array([1, 2, 3])

In [38]:
a1[0]

1

In [41]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
a2[0]

array([1, 2, 3])

In [43]:
a2[1]

array([4, 5, 6])

In [44]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [45]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
a3[:2,:1,:3] # Slicing

array([[[ 1,  2,  3]],

       [[10, 11, 12]]])

In [49]:
np.random.seed(seed=120)
a4 = np.random.randint(10, size=(2,3,4,5))

In [50]:
a4

array([[[[7, 0, 8, 4, 1],
         [7, 1, 3, 8, 9],
         [4, 9, 9, 6, 7],
         [9, 1, 9, 4, 5]],

        [[7, 2, 2, 2, 0],
         [0, 7, 4, 2, 2],
         [4, 8, 5, 6, 4],
         [1, 9, 2, 0, 5]],

        [[7, 5, 7, 8, 4],
         [2, 1, 6, 9, 5],
         [6, 1, 5, 7, 8],
         [7, 4, 8, 9, 7]]],


       [[[8, 5, 6, 0, 5],
         [8, 6, 8, 5, 4],
         [1, 9, 4, 5, 7],
         [9, 1, 2, 9, 5]],

        [[5, 8, 9, 2, 1],
         [6, 1, 6, 4, 4],
         [7, 8, 2, 8, 7],
         [3, 4, 4, 5, 3]],

        [[8, 6, 1, 6, 5],
         [5, 3, 6, 6, 4],
         [6, 8, 8, 5, 6],
         [3, 3, 7, 8, 0]]]])

In [52]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [55]:
a4[:,:,:,:4]

array([[[[7, 0, 8, 4],
         [7, 1, 3, 8],
         [4, 9, 9, 6],
         [9, 1, 9, 4]],

        [[7, 2, 2, 2],
         [0, 7, 4, 2],
         [4, 8, 5, 6],
         [1, 9, 2, 0]],

        [[7, 5, 7, 8],
         [2, 1, 6, 9],
         [6, 1, 5, 7],
         [7, 4, 8, 9]]],


       [[[8, 5, 6, 0],
         [8, 6, 8, 5],
         [1, 9, 4, 5],
         [9, 1, 2, 9]],

        [[5, 8, 9, 2],
         [6, 1, 6, 4],
         [7, 8, 2, 8],
         [3, 4, 4, 5]],

        [[8, 6, 1, 6],
         [5, 3, 6, 6],
         [6, 8, 8, 5],
         [3, 3, 7, 8]]]])

In [56]:
a5 = np.random.randint(10, 50, size=(2,3,4,5,6))

In [57]:
a5

array([[[[[26, 37, 34, 11, 18, 33],
          [24, 11, 13, 40, 15, 25],
          [13, 28, 29, 43, 21, 33],
          [32, 17, 27, 32, 32, 14],
          [23, 20, 29, 48, 12, 25]],

         [[46, 19, 32, 39, 46, 37],
          [14, 47, 26, 28, 22, 17],
          [23, 25, 11, 39, 35, 36],
          [44, 41, 16, 14, 28, 34],
          [30, 18, 44, 25, 37, 36]],

         [[30, 21, 32, 37, 20, 18],
          [35, 20, 16, 24, 16, 35],
          [18, 38, 48, 30, 29, 33],
          [41, 21, 37, 29, 26, 13],
          [30, 38, 46, 36, 20, 10]],

         [[37, 11, 44, 15, 49, 48],
          [47, 39, 40, 29, 37, 26],
          [27, 18, 19, 30, 42, 16],
          [17, 26, 12, 32, 17, 33],
          [37, 42, 42, 38, 10, 46]]],


        [[[31, 38, 22, 36, 33, 12],
          [33, 30, 17, 12, 47, 12],
          [39, 25, 46, 35, 20, 10],
          [16, 40, 33, 41, 39, 12],
          [35, 18, 31, 21, 21, 26]],

         [[49, 48, 39, 16, 28, 15],
          [12, 30, 46, 40, 47, 48],
          [30, 2

In [58]:
a5[:1,:2,:,:4,:3]

array([[[[[26, 37, 34],
          [24, 11, 13],
          [13, 28, 29],
          [32, 17, 27]],

         [[46, 19, 32],
          [14, 47, 26],
          [23, 25, 11],
          [44, 41, 16]],

         [[30, 21, 32],
          [35, 20, 16],
          [18, 38, 48],
          [41, 21, 37]],

         [[37, 11, 44],
          [47, 39, 40],
          [27, 18, 19],
          [17, 26, 12]]],


        [[[31, 38, 22],
          [33, 30, 17],
          [39, 25, 46],
          [16, 40, 33]],

         [[49, 48, 39],
          [12, 30, 46],
          [30, 24, 20],
          [46, 13, 15]],

         [[35, 21, 30],
          [25, 46, 16],
          [35, 47, 18],
          [46, 21, 38]],

         [[47, 28, 11],
          [38, 48, 18],
          [42, 37, 26],
          [32, 29, 45]]]]])