In [1]:
import numpy as np

## 1. Datatypes and Attributes

In [2]:
#Numpys main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],[4,5,6]])

In [5]:
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               
               [[10,11,12],[13,14,15],[16,17,18]]])

In [6]:
a2
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
a2
import pandas as pd

In [15]:
df = pd.DataFrame(a2)

In [16]:
df

0  1  2
0  1  2  3
1  4  5  6

# 2. Creating Numpy Arrays

In [17]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int64')

In [20]:
ones = np.ones((2,3))

In [21]:
ones


array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones.dtype

dtype('float64')

In [23]:
type(ones)

numpy.ndarray

In [24]:
zeros = np.zeros((2,3))

In [25]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
range_array = np.arange(0,10,3)

In [27]:
range_array

array([0, 3, 6, 9])

In [30]:
random_array = np.random.randint(0,100, size = (5,6))

In [31]:
random_array

array([[54, 44, 52, 83, 78, 66],
       [45, 22, 77, 84,  6, 44],
       [45, 13, 58, 57, 27, 77],
       [60, 97, 78, 78,  7, 10],
       [41, 80, 87, 58, 38, 74]])

In [34]:
random_arr2 = np.random.random((3,4))

In [35]:
random_arr2.shape

(3, 4)

In [36]:
random_arr3 = np.random.rand(5,3)

In [37]:
random_arr3

array([[0.19262714, 0.1449036 , 0.65196728],
       [0.21188291, 0.6239468 , 0.32458004],
       [0.52944307, 0.57101645, 0.62582996],
       [0.55497472, 0.58774211, 0.33081014],
       [0.70934812, 0.44030321, 0.03416647]])

In [38]:
# Psuedo-random numbers

In [42]:
np.random.seed(seed= 7)
random_arr5 = np.random.random((5,3))
random_arr5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])