In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2025-07-05 11:44:57.104942: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-07-05 11:44:57.112062: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1751696097.120413   17190 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1751696097.122988   17190 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1751696097.129150   17190 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2857, 950, 6313, 589],
 [2857, 950, 6313, 8871],
 [2857, 9959, 6313, 1411],
 [1787, 4722, 8275, 9645, 3401],
 [1787, 4722, 8275, 9645, 2610],
 [8431, 2857, 1605, 6313, 778],
 [7101, 8649, 1032, 9645]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2857  950 6313  589]
 [   0    0    0    0 2857  950 6313 8871]
 [   0    0    0    0 2857 9959 6313 1411]
 [   0    0    0 1787 4722 8275 9645 3401]
 [   0    0    0 1787 4722 8275 9645 2610]
 [   0    0    0 8431 2857 1605 6313  778]
 [   0    0    0    0 7101 8649 1032 9645]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()

model.add(Embedding(voc_size,dim))
model.build((None,sent_length ))
model.compile('adam','mse')

I0000 00:00:1751696098.496411   17190 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9279 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4070 SUPER, pci bus id: 0000:01:00.0, compute capability: 8.9


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step


I0000 00:00:1751696098.968087   17338 service.cc:152] XLA service 0x715cdc003120 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1751696098.968101   17338 service.cc:160]   StreamExecutor device (0): NVIDIA GeForce RTX 4070 SUPER, Compute Capability 8.9
I0000 00:00:1751696098.974004   17338 cuda_dnn.cc:529] Loaded cuDNN version 91002
I0000 00:00:1751696099.020466   17338 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


array([[[ 0.00711452,  0.00733985,  0.02747783,  0.04355154,
         -0.04977702, -0.03959248, -0.00355226, -0.03311235,
          0.00366913,  0.03864921],
        [ 0.00711452,  0.00733985,  0.02747783,  0.04355154,
         -0.04977702, -0.03959248, -0.00355226, -0.03311235,
          0.00366913,  0.03864921],
        [ 0.00711452,  0.00733985,  0.02747783,  0.04355154,
         -0.04977702, -0.03959248, -0.00355226, -0.03311235,
          0.00366913,  0.03864921],
        [ 0.00711452,  0.00733985,  0.02747783,  0.04355154,
         -0.04977702, -0.03959248, -0.00355226, -0.03311235,
          0.00366913,  0.03864921],
        [ 0.00012126,  0.02346918,  0.04877954, -0.03591298,
         -0.04396044, -0.0386856 , -0.0168656 ,  0.01911117,
          0.01447851, -0.04620352],
        [-0.00654273, -0.01966271, -0.01356839, -0.04932113,
          0.04391326, -0.02635979, -0.02611834, -0.02087054,
         -0.04669993,  0.00187136],
        [ 0.04024649, -0.03963844, -0.02508347, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 2857,  950, 6313,  589], dtype=int32)

In [22]:
model.predict(np.expand_dims(embedded_docs[0], axis = 0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step


array([[[ 0.00711452,  0.00733985,  0.02747783,  0.04355154,
         -0.04977702, -0.03959248, -0.00355226, -0.03311235,
          0.00366913,  0.03864921],
        [ 0.00711452,  0.00733985,  0.02747783,  0.04355154,
         -0.04977702, -0.03959248, -0.00355226, -0.03311235,
          0.00366913,  0.03864921],
        [ 0.00711452,  0.00733985,  0.02747783,  0.04355154,
         -0.04977702, -0.03959248, -0.00355226, -0.03311235,
          0.00366913,  0.03864921],
        [ 0.00711452,  0.00733985,  0.02747783,  0.04355154,
         -0.04977702, -0.03959248, -0.00355226, -0.03311235,
          0.00366913,  0.03864921],
        [ 0.00012126,  0.02346918,  0.04877954, -0.03591298,
         -0.04396044, -0.0386856 , -0.0168656 ,  0.01911117,
          0.01447851, -0.04620352],
        [-0.00654273, -0.01966271, -0.01356839, -0.04932113,
          0.04391326, -0.02635979, -0.02611834, -0.02087054,
         -0.04669993,  0.00187136],
        [ 0.04024649, -0.03963844, -0.02508347, -0.0