# Introduction to TensorFlow

In [2]:
import tensorflow as tf

2025-02-17 19:42:53.782635: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-17 19:42:53.906038: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1739801573.952461   14275 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1739801573.965834   14275 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-17 19:42:54.081553: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

In [3]:
tf.__version__

'2.18.0'

In [4]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

I0000 00:00:1739801575.954982   14275 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9225 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4070 SUPER, pci bus id: 0000:01:00.0, compute capability: 8.9


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
import numpy as np

arr = np.array([2,5,23,234])
ten = tf.constant(arr)
ten

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([  2,   5,  23, 234])>

In [6]:
ten.ndim

1

In [7]:
arr = np.array([[2,5,23,234],
                [2,5,23,234]])
mat = tf.constant(arr,dtype=tf.float16)
mat

2025-02-17 19:42:56.043750: E tensorflow/core/util/util.cc:131] oneDNN supports DT_HALF only on platforms with AVX-512. Falling back to the default Eigen-based implementation if present.


<tf.Tensor: shape=(2, 4), dtype=float16, numpy=
array([[  2.,   5.,  23., 234.],
       [  2.,   5.,  23., 234.]], dtype=float16)>

In [8]:
mat.ndim

2

In [9]:
# creating tensors using tf.variable()

changable_tensor = tf.Variable([10,7],dtype = tf.int16)
unchangable_tensor = tf.constant([10,7],dtype = tf.int16)
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int16, numpy=array([10,  7], dtype=int16)>,
 <tf.Tensor: shape=(2,), dtype=int16, numpy=array([10,  7], dtype=int16)>)

In [10]:
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int16, numpy=array([7, 7], dtype=int16)>