# Introduction to TensorFlow

In [2]:
import tensorflow as tf

2025-02-26 11:20:38.204892: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-26 11:20:38.211849: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1740549038.220422   29640 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1740549038.222890   29640 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-26 11:20:38.231448: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

In [3]:
tf.__version__

'2.18.0'

In [4]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

I0000 00:00:1740549039.390567   29640 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9579 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4070 SUPER, pci bus id: 0000:01:00.0, compute capability: 8.9


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
import numpy as np

arr = np.array([2,5,23,234])
ten = tf.constant(arr)
ten

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([  2,   5,  23, 234])>

In [6]:
ten.ndim

1

In [7]:
arr = np.array([[2,5,23,234],
                [2,5,23,234]])
mat = tf.constant(arr,dtype=tf.float16)
mat

2025-02-26 11:20:39.478894: E tensorflow/core/util/util.cc:131] oneDNN supports DT_HALF only on platforms with AVX-512. Falling back to the default Eigen-based implementation if present.


<tf.Tensor: shape=(2, 4), dtype=float16, numpy=
array([[  2.,   5.,  23., 234.],
       [  2.,   5.,  23., 234.]], dtype=float16)>

In [8]:
mat.ndim

2

In [9]:
# creating tensors using tf.variable()

changable_tensor = tf.Variable([10,7],dtype = tf.int16)
unchangable_tensor = tf.constant([10,7],dtype = tf.int16)
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int16, numpy=array([10,  7], dtype=int16)>,
 <tf.Tensor: shape=(2,), dtype=int16, numpy=array([10,  7], dtype=int16)>)

In [10]:
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int16, numpy=array([7, 7], dtype=int16)>

# Creating random tensors

Tensors of some arbitrary size with random numbers.

In [11]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [12]:
random2 = tf.random.Generator.from_seed(42)
random2 = tf.random.normal(shape=(3,2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7198522 ,  0.69583267],
       [-0.3715841 , -0.05305022],
       [ 1.0502383 ,  1.6508129 ]], dtype=float32)>

In [13]:
random1 == random2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

# Shuffle the order of elements in a tensor

In [14]:
not_shuffled = tf.random.normal(shape=(3,2),dtype='float16')
not_shuffled.ndim
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[-0.441 , -0.371 ],
       [ 0.3987, -0.938 ],
       [ 1.398 , -0.0466]], dtype=float16)>

In [15]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 1.398 , -0.0466],
       [ 0.3987, -0.938 ],
       [-0.441 , -0.371 ]], dtype=float16)>

In [16]:
tf.random.set_seed(42)
not_shuffled = tf.random.normal(shape=(3,2),dtype='float16')
not_shuffled.ndim
not_shuffled
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[-2.389 , -1.039 ],
       [ 0.3274, -0.843 ],
       [ 0.3193, -1.407 ]], dtype=float16)>

# Creating tensors from numpy arrays

In [17]:
import numpy as np

arr = np.random.randint(0,200, size = (5,4))
tens = tf.constant(arr)
tens

<tf.Tensor: shape=(5, 4), dtype=int64, numpy=
array([[183, 148,  80, 105],
       [  4, 112, 136, 127],
       [ 49,  31, 138,  32],
       [ 82,  57,  30, 161],
       [150, 101, 135,  86]])>

# Getting information from Tensors

In [18]:
print("The datatype of every element is: ", tens.dtype)
print("The number of dimensions is: ", tens.ndim)

The datatype of every element is:  <dtype: 'int64'>
The number of dimensions is:  2


In [19]:
print("The total number of elements in our tensor is : " ,tf.size(tens).numpy())
print("The total number of elements in our tensor is : " ,tf.size(tens))

The total number of elements in our tensor is :  20
The total number of elements in our tensor is :  tf.Tensor(20, shape=(), dtype=int32)


In [20]:
rank_2_tensor = tf.random.Generator.from_seed(42)
rank_2_tensor = tf.random.normal(shape = (2,2))

In [21]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.5590974, -0.5347214],
       [ 2.3730333, -1.5725931]], dtype=float32)>

In [22]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis] # "..."" means all the previous dimensions

In [23]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[-0.5590974],
        [-0.5347214]],

       [[ 2.3730333],
        [-1.5725931]]], dtype=float32)>

In [24]:
tf.expand_dims(rank_3_tensor,axis = -1)

<tf.Tensor: shape=(2, 2, 1, 1), dtype=float32, numpy=
array([[[[-0.5590974]],

        [[-0.5347214]]],


       [[[ 2.3730333]],

        [[-1.5725931]]]], dtype=float32)>

In [25]:
t = tf.random.Generator.from_seed(42)
t = t.normal(shape = (2,2))
t = t +10

In [26]:
t

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 9.24342 ,  9.931453],
       [10.075951,  8.742616]], dtype=float32)>

In [27]:
tf.multiply(t,10)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 92.4342  ,  99.31453 ],
       [100.75951 ,  87.426155]], dtype=float32)>

In [28]:
tf.add(t,10)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19.24342 , 19.931454],
       [20.07595 , 18.742615]], dtype=float32)>

# Matrix multiplication

In [29]:
tf.matmul(random1,tf.reshape(random2, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.5482624 , -0.598444  ,  0.1679749 ],
       [ 0.01203156, -1.2677045 , -2.1039283 ],
       [ 0.2630234 , -2.063146  , -2.9030838 ]], dtype=float32)>

In [30]:
random1 @ tf.reshape(random2, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.5482624 , -0.598444  ,  0.1679749 ],
       [ 0.01203156, -1.2677045 , -2.1039283 ],
       [ 0.2630234 , -2.063146  , -2.9030838 ]], dtype=float32)>

In [31]:
tf.tensordot(random1, tf.reshape(random2, shape=(2,3)), axes=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.5482624 , -0.598444  ,  0.1679749 ],
       [ 0.01203156, -1.2677045 , -2.1039283 ],
       [ 0.2630234 , -2.063146  , -2.9030838 ]], dtype=float32)>

In [32]:
y = random1

print("Normal Y\n", y)
print("\n")
print("Y Transposed\n", tf.transpose(y))
print("\n")

print("Y Reshaped\n", tf.reshape(y, shape=(2,3)))

Normal Y
 tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193765 -1.8107855 ]], shape=(3, 2), dtype=float32)


Y Transposed
 tf.Tensor(
[[-0.7565803   0.07595026 -0.23193765]
 [-0.06854702 -1.2573844  -1.8107855 ]], shape=(2, 3), dtype=float32)


Y Reshaped
 tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193765 -1.8107855 ]], shape=(2, 3), dtype=float32)


# Changing Data types of Tensors

In [35]:
x = tf.cast(random1, dtype = tf.float16)

In [36]:
x

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[-0.7563 , -0.06854],
       [ 0.0759 , -1.258  ],
       [-0.2319 , -1.811  ]], dtype=float16)>

In [37]:
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

# Aggregating tensors

In [40]:
d = tf.constant([-7,-10])

In [41]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [43]:
rt = tf.random.Generator.from_seed(42)
rt = tf.random.normal(shape = (3,2))

In [44]:
tf.reduce_min(rt)

<tf.Tensor: shape=(), dtype=float32, numpy=-0.7410268783569336>

In [46]:
tf.reduce_sum(rt)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0608793497085571>