# Introduction to TensorFlow

In [30]:
import tensorflow as tf

In [31]:
tf.__version__

'2.18.0'

In [32]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [33]:
import numpy as np

arr = np.array([2,5,23,234])
ten = tf.constant(arr)
ten

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([  2,   5,  23, 234])>

In [34]:
ten.ndim

1

In [35]:
arr = np.array([[2,5,23,234],
                [2,5,23,234]])
mat = tf.constant(arr,dtype=tf.float16)
mat

<tf.Tensor: shape=(2, 4), dtype=float16, numpy=
array([[  2.,   5.,  23., 234.],
       [  2.,   5.,  23., 234.]], dtype=float16)>

In [36]:
mat.ndim

2

In [37]:
# creating tensors using tf.variable()

changable_tensor = tf.Variable([10,7],dtype = tf.int16)
unchangable_tensor = tf.constant([10,7],dtype = tf.int16)
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int16, numpy=array([10,  7], dtype=int16)>,
 <tf.Tensor: shape=(2,), dtype=int16, numpy=array([10,  7], dtype=int16)>)

In [38]:
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int16, numpy=array([7, 7], dtype=int16)>

# Creating random tensors

Tensors of some arbitrary size with random numbers.

In [39]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [40]:
random2 = tf.random.Generator.from_seed(42)
random2 = tf.random.normal(shape=(3,2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.34924588,  1.7806982 ],
       [-0.35074225,  0.6456978 ],
       [-1.3639455 , -0.7317337 ]], dtype=float32)>

In [41]:
random1 == random2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

# Shuffle the order of elements in a tensor

In [53]:
not_shuffled = tf.random.normal(shape=(3,2),dtype='float16')
not_shuffled.ndim
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 0.968 , -0.3804],
       [-0.913 , -0.1924],
       [ 0.4626,  1.699 ]], dtype=float16)>

In [54]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 0.968 , -0.3804],
       [ 0.4626,  1.699 ],
       [-0.913 , -0.1924]], dtype=float16)>

In [61]:
tf.random.set_seed(42)
not_shuffled = tf.random.normal(shape=(3,2),dtype='float16')
not_shuffled.ndim
not_shuffled
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[-2.389 , -1.039 ],
       [ 0.3274, -0.843 ],
       [ 0.3193, -1.407 ]], dtype=float16)>

# Creating tensors from numpy arrays

In [79]:
import numpy as np

arr = np.random.randint(0,200, size = (5,4))
tens = tf.constant(arr)
tens

<tf.Tensor: shape=(5, 4), dtype=int64, numpy=
array([[ 12,  57,  29, 115],
       [ 66,  23,  46, 122],
       [120, 165, 173, 170],
       [135, 171,   1,  80],
       [109,  49, 131,  55]])>

# Getting information from Tensors