# Introduction to TensorFlow

In [1]:
import tensorflow as tf

2025-02-16 12:21:34.344535: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-16 12:21:34.468806: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1739688694.514585   38414 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1739688694.527776   38414 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-16 12:21:34.644394: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

In [2]:
tf.__version__

'2.18.0'

In [4]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [10]:
import numpy as np

arr = np.array([2,5,23,234])
ten = tf.constant(arr)
ten

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([  2,   5,  23, 234])>

In [9]:
ten.ndim

1

In [20]:
arr = np.array([[2,5,23,234],
                [2,5,23,234]])
mat = tf.constant(arr,dtype=tf.float16)
mat

2025-02-16 12:25:07.915393: E tensorflow/core/util/util.cc:131] oneDNN supports DT_HALF only on platforms with AVX-512. Falling back to the default Eigen-based implementation if present.


<tf.Tensor: shape=(2, 4), dtype=float16, numpy=
array([[  2.,   5.,  23., 234.],
       [  2.,   5.,  23., 234.]], dtype=float16)>

In [21]:
mat.ndim

2

In [27]:
# creating tensors using tf.variable()

changable_tensor = tf.Variable([10,7],dtype = tf.int16)
unchangable_tensor = tf.constant([10,7],dtype = tf.int16)
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int16, numpy=array([10,  7], dtype=int16)>,
 <tf.Tensor: shape=(2,), dtype=int16, numpy=array([10,  7], dtype=int16)>)

In [28]:
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int16, numpy=array([7, 7], dtype=int16)>