
About Dataset

Context This is a small subset of dataset of Book reviews from Amazon Kindle Store category.

Content 5-core dataset of product reviews from Amazon Kindle Store category from May 1996 - July 2014. Contains total of 982619 entries. Each reviewer has at least 5 reviews and each product has at least 5 reviews in this dataset. Columns

    asin - ID of the product, like B000FA64PK
    helpful - helpfulness rating of the review - example: 2/3.
    overall - rating of the product.
    reviewText - text of the review (heading).
    reviewTime - time of the review (raw).
    reviewerID - ID of the reviewer, like A3SPTOKDG7WBLN
    reviewerName - name of the reviewer.
    summary - summary of the review (description).
    unixReviewTime - unix timestamp.

Acknowledgements This dataset is taken from Amazon product data, Julian McAuley, UCSD website. http://jmcauley.ucsd.edu/data/amazon/

License to the data files belong to them.

Inspiration

    Sentiment analysis on reviews.
    Understanding how people rate usefulness of a review/ What factors influence helpfulness of a review.
    Fake reviews/ outliers.
    Best rated product IDs, or similarity between products based on reviews alone (not the best idea ikr).
    Any other interesting analysis

Best Practises

    Preprocessing And Cleaning
    Train Test Split
    BOW,TFIDF,Word2vec
    Train ML algorithms



In [62]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from bs4 import BeautifulSoup



In [63]:
df = pd.read_csv('all_kindle_review.csv')

In [64]:
df

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0                 0       11539  B0033UV8HI  [8, 10]       3   
1                 1        5957  B002HJV4DE   [1, 1]       5   
2                 2        9146  B002ZG96I4   [0, 0]       3   
3                 3        7038  B002QHWOEU   [1, 3]       3   
4                 4        1776  B001A06VJ8   [0, 1]       4   
...             ...         ...         ...      ...     ...   
11995         11995        2183  B001DUGORO   [0, 0]       4   
11996         11996        6272  B002JCSFSQ   [2, 2]       5   
11997         11997       12483  B0035N1V7K   [0, 1]       3   
11998         11998        3640  B001W1XT40   [1, 2]       1   
11999         11999       11398  B003370JUS   [5, 6]       3   

                                              reviewText   reviewTime  \
0      Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1      Great short read.  I didn't want to put it dow...   10 8, 2013   
2      I'll start by saying this is the first of four...  04 11, 2014   
3      Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4      I did not expect this type of book to be in li...  12 31, 2012   
...                                                  ...          ...   
11995  Valentine cupid is a vampire- Jena and Ian ano...  02 28, 2014   
11996  I have read all seven books in this series. Ap...  05 16, 2011   
11997  This book really just wasn't my cuppa.  The si...  07 26, 2013   
11998  tried to use it to charge my kindle, it didn't...  09 17, 2013   
11999  Taking Instruction is a look into the often hi...   07 5, 2012   

           reviewerID                   reviewerName  \
0      A3HHXRELK8BHQG                         Ridley   
1      A2RGNZ0TRF578I                   Holly Butler   
2      A3S0H2HV6U1I7F                        Merissa   
3       AC4OQW3GZ919J                     Cleargrace   
4      A3C9V987IQHOQD                       Rjostler   
...               ...                            ...   
11995  A1OKS5Q1HD8WQC                  lisa jon jung   
11996   AQRSPXLNEQAMA                        TerryLP   
11997  A2T5QLT5VXOJAK                        hwilson   
11998  A28MHD2DDY6DXB  Allison A. Slater "Gryphon50"   
11999  A3JUXLB4K9ZXCC                      Dafna Yee   

                                                 summary  unixReviewTime  
0                               Entertaining But Average      1283385600  
1                                Terrific menage scenes!      1381190400  
2                                       Snapdragon Alley      1397174400  
3                                 very light murder cozy      1404518400  
4                                                   Book      1356912000  
...                                                  ...             ...  
11995                                               jena      1393545600  
11996                                Peacekeepers Series      1305504000  
11997                                    a little creepy      1374796800  
11998                                        didn't work      1379376000  
11999  If you like BDSM with a touch of romance, this...      1341446400  

[12000 rows x 11 columns]

In [65]:
df = df[['reviewText', 'rating']]

In [66]:
df.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [67]:
df.shape

(12000, 2)

In [68]:
df.isna().sum()

reviewText    0
rating        0
dtype: int64

In [69]:
df['rating'].unique()

array([3, 5, 4, 2, 1])

In [70]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

### **Preprocessing and Cleaning**

In [71]:
df['rating'] = df['rating'].apply(lambda x : 0 if x<3 else 1)

/tmp/ipykernel_9661/874010074.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating'] = df['rating'].apply(lambda x : 0 if x<3 else 1)


In [72]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [73]:
df['reviewText']  = df['reviewText'].str.lower()

/tmp/ipykernel_9661/996257607.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']  = df['reviewText'].str.lower()


In [74]:
df.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

### **Data Cleaning**

In [75]:
df['reviewText'] = df['reviewText'].apply(lambda x:re.sub('[^^a-z A-Z 0-9]+', '', x))

/tmp/ipykernel_9661/3551487871.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].apply(lambda x:re.sub('[^^a-z A-Z 0-9]+', '', x))


In [76]:
df['reviewText'] = df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))

/tmp/ipykernel_9661/349245991.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))


In [77]:
df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))


/tmp/ipykernel_9661/2015794547.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))


In [78]:
df['reviewText'] = df['reviewText'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())

/tmp/ipykernel_9661/4311170.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())


In [79]:
df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))

/tmp/ipykernel_9661/731363273.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))


In [80]:
df.head()

reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [81]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [82]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [83]:
df['reviewText']=df['reviewText'].apply(lambda x: lemmatize_words(x))

/tmp/ipykernel_9661/3266273754.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x: lemmatize_words(x))


In [84]:
from sklearn.model_selection import train_test_split

In [85]:
X_train,X_test,y_train,y_test = train_test_split(df['reviewText'], df['rating'], test_size=0.20)

In [86]:
from sklearn.feature_extraction.text import CountVectorizer

In [87]:
bow = CountVectorizer()

In [88]:
X_train_bow = bow.fit_transform(X_train).toarray()

In [89]:
X_test_bow = bow.transform(X_test).toarray()

In [90]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf = tfidf.transform(X_test).toarray()

In [91]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [92]:
from sklearn.naive_bayes import GaussianNB

In [93]:
nb_model_bow = GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf = GaussianNB().fit(X_train_tfidf,y_train)

In [94]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [95]:
y_pred_bow = nb_model_bow.predict(X_test_bow)

In [96]:
y_pred_tfidf= nb_model_bow.predict(X_test_tfidf)

In [97]:
print("BOW Accuracy: ", accuracy_score(y_test, y_pred_bow))

BOW Accuracy:  0.58125


In [98]:
print(confusion_matrix(y_test, y_pred_bow))

[[514 284]
 [721 881]]


In [99]:
print("TFIDF Accuracy: ", accuracy_score(y_test, y_pred_tfidf))

TFIDF Accuracy:  0.5804166666666667


In [100]:
print(confusion_matrix(y_test, y_pred_tfidf))

[[506 292]
 [715 887]]


In [101]:
print(classification_report(y_test, y_pred_tfidf))

              precision    recall  f1-score   support

           0       0.41      0.63      0.50       798
           1       0.75      0.55      0.64      1602

    accuracy                           0.58      2400
   macro avg       0.58      0.59      0.57      2400
weighted avg       0.64      0.58      0.59      2400



In [102]:
from gensim.models import Word2Vec
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
wnl = WordNetLemmatizer()

In [103]:
df.head()

reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [104]:

w2v_model = Word2Vec(sentences=df['reviewText'], vector_size=300, window=5, min_count=2, workers=4, epochs=20)


def get_avg_word2vec(tokens, model, vector_size):
    embeddings = [model.wv[word] for word in tokens if word in model.wv]
    if len(embeddings) == 0: 
        return np.zeros(vector_size)
    return np.mean(embeddings, axis=0)


In [106]:
import numpy as np
vector_size = 300
df['features'] = df['reviewText'].apply(lambda x: get_avg_word2vec(x, w2v_model, vector_size))

# Convert the features column into a NumPy array for modeling
X = np.vstack(df['features'].values)


/tmp/ipykernel_9661/1412478705.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['features'] = df['reviewText'].apply(lambda x: get_avg_word2vec(x, w2v_model, vector_size))


In [107]:
# Assuming 'label' is the target column for classification
y = df['rating'].values  # Replace 'label' with your target column name

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [108]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

# Predict on the test set
y_pred = clf.predict(X_test)


In [109]:
# Print classification metrics
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.6658333333333334
Classification Report:
               precision    recall  f1-score   support

           0       0.50      0.14      0.22       803
           1       0.68      0.93      0.79      1597

    accuracy                           0.67      2400
   macro avg       0.59      0.54      0.50      2400
weighted avg       0.62      0.67      0.60      2400



In [110]:
df.head(20)

reviewText  rating  \
0   jace rankin may short he nothing mess man haul...       1   
1   great short read didnt want put read one sitti...       1   
2   ill start saying first four book wasnt expecti...       1   
3   aggie angela lansbury carry pocketbook instead...       1   
4   expect type book library pleased find price right       1   
5   aislinn little girl big dream death older brot...       1   
6   making good story unfortunately disappointsit ...       0   
7   got like collaborated short story alot time tw...       1   
8   loved book hooked series hope kelsey maxwell r...       1   
9   thats good thing short sweet tease give everyt...       1   
10  received copy book review secret society fanat...       0   
11  even though already know outcome still enjoyab...       1   
12  read review decided give try despite review la...       0   
13  finished reread wicked garden say wow even nov...       1   
14  king james version far tell may know 1611 kjv ...       1   
15  disappointed book anything blond one figured 5...       0   
16  super quick book wish would longer really like...       1   
17  many time author going get amazon delete add c...       0   
18  love jr ward book story completely awsome zsad...       1   
19  first author thoroughly enjoyed iti say concep...       1   

                                             features  
0   [0.07710363, -0.05014663, 0.04704434, -0.00139...  
1   [0.058643878, -0.039134175, 0.058156658, 0.008...  
2   [0.06670615, -0.029150214, 0.03179433, -0.0212...  
3   [0.10576137, -0.058694758, 0.06331291, 0.01168...  
4   [0.09811809, -0.0138768, 0.075832054, 0.010857...  
5   [0.07945215, -0.04896187, 0.04113943, -0.00218...  
6   [0.05247315, -0.033264287, 0.06979315, 0.00977...  
7   [0.05743053, -0.04119679, 0.07223986, 0.005971...  
8   [0.060038377, -0.052558836, 0.063253604, 0.000...  
9   [0.025032574, -0.04087352, 0.043399636, 0.0071...  
10  [0.072694145, -0.043639448, 0.09751176, 0.0175...  
11  [0.050157376, -0.047654517, 0.08757069, 0.0040...  
12  [0.11338506, -0.06679194, 0.058804147, 0.00625...  
13  [0.07129635, -0.04269717, 0.05504021, -0.00147...  
14  [0.07503705, -0.06265112, 0.02588809, -0.00399...  
15  [0.065996386, -0.052249413, 0.029073691, -0.01...  
16  [0.06418447, -0.04160963, 0.0438166, -0.007456...  
17  [0.08471943, -0.053475313, 0.08172887, 0.01790...  
18  [0.048597265, -0.024467062, 0.035090644, -0.00...  
19  [0.06085104, -0.033213392, 0.057702385, 0.0061...

In [111]:
df['features'][1]

array([ 5.86438775e-02, -3.91341746e-02,  5.81566580e-02,  8.51483084e-03,
       -4.56769727e-02, -8.90014619e-02, -4.92667034e-03,  9.37074330e-03,
       -5.79264760e-02,  6.01703823e-02, -5.88222453e-03, -9.21399239e-03,
       -4.76080645e-03, -5.10470755e-02, -4.60236222e-02,  4.61870432e-02,
       -1.20519204e-02,  1.82161983e-02,  5.42591140e-02, -5.28790578e-02,
        2.88611911e-02, -2.67466288e-02,  3.01528852e-02, -7.43439049e-02,
       -2.73390990e-02, -5.08542284e-02,  9.21592768e-03, -7.26802042e-03,
        2.75604445e-02, -8.72816518e-02,  8.55335221e-02, -2.24691518e-02,
        8.81183594e-02, -1.57913193e-02,  1.57783069e-02, -3.38024311e-02,
        4.52070013e-02, -1.59591716e-02, -2.43460238e-02, -6.78110421e-02,
        1.46678425e-02, -7.18758926e-02,  6.20402209e-02, -5.78501001e-02,
       -7.39179179e-03,  4.72676009e-02, -2.87069231e-02, -4.68664095e-02,
        4.80017811e-02, -3.74289863e-02, -5.25697507e-02, -7.19723612e-05,
        8.68518464e-03,  